---
meta:
  name: homebrew-kubernetes
  target: pipes@main
  # url: https://ci2.starkandwayne.com team: starkandwayne

  github:
    owner: starkandwayne
    repo: homebrew-kubernetes
    private_key: ((github.private-key))
    access_token: ((github.access-token))
